/**
 * Do not edit directly, this file was auto-generated.
 */

export const ColorBaseWhite = "#ffffff";
export const ColorBaseBlack = "#000000";
export const ColorBaseOverlay = "#00000080"; // 50% black for modal overlays
export const ColorBaseSlate50 = "#f8fafc";
export const ColorBaseSlate100 = "#f1f5f9";
export const ColorBaseSlate200 = "#e2e8f0";
export const ColorBaseSlate300 = "#cbd5e1";
export const ColorBaseSlate400 = "#94a3b8";
export const ColorBaseSlate500 = "#64748b";
export const ColorBaseSlate600 = "#475569";
export const ColorBaseSlate700 = "#334155";
export const ColorBaseSlate800 = "#1e293b";
export const ColorBaseSlate900 = "#0f172a";
export const ColorBaseSlate950 = "#020617";
export const ColorBaseStone50 = "#fafaf9";
export const ColorBaseStone100 = "#f5f5f4";
export const ColorBaseStone200 = "#e7e5e4";
export const ColorBaseStone300 = "#d6d3d1";
export const ColorBaseStone400 = "#a8a29e";
export const ColorBaseStone500 = "#78716c";
export const ColorBaseStone600 = "#57534e";
export const ColorBaseStone700 = "#44403c";
export const ColorBaseStone800 = "#292524";
export const ColorBaseStone900 = "#1c1917";
export const ColorBaseStone950 = "#0c0a09";
export const ColorBaseZinc50 = "#fafafa";
export const ColorBaseZinc100 = "#f4f4f5";
export const ColorBaseZinc200 = "#e4e4e7";
export const ColorBaseZinc300 = "#d4d4d8";
export const ColorBaseZinc400 = "#a1a1aa";
export const ColorBaseZinc500 = "#71717a";
export const ColorBaseZinc600 = "#52525b";
export const ColorBaseZinc700 = "#3f3f46";
export const ColorBaseZinc800 = "#27272a";
export const ColorBaseZinc900 = "#18181b";
export const ColorBaseZinc950 = "#09090b";
export const ColorBaseSky50 = "#f0f9ff";
export const ColorBaseSky100 = "#e0f2fe";
export const ColorBaseSky200 = "#bae6fd";
export const ColorBaseSky300 = "#7dd3fc";
export const ColorBaseSky400 = "#38bdf8";
export const ColorBaseSky500 = "#0ea5e9";
export const ColorBaseSky600 = "#0284c7";
export const ColorBaseSky700 = "#0369a1";
export const ColorBaseSky800 = "#075985";
export const ColorBaseSky900 = "#0c4a6e";
export const ColorBaseSky950 = "#082f49";
export const ColorBaseCyan50 = "#ecfeff";
export const ColorBaseCyan100 = "#cffafe";
export const ColorBaseCyan200 = "#a5f3fc";
export const ColorBaseCyan300 = "#67e8f9";
export const ColorBaseCyan400 = "#22d3ee";
export const ColorBaseCyan500 = "#06b6d4";
export const ColorBaseCyan600 = "#0891b2";
export const ColorBaseCyan700 = "#0e7490";
export const ColorBaseCyan800 = "#155e75";
export const ColorBaseCyan900 = "#164e63";
export const ColorBaseCyan950 = "#083344";
export const ColorBaseTeal50 = "#f0fdfa";
export const ColorBaseTeal100 = "#ccfbf1";
export const ColorBaseTeal200 = "#99f6e4";
export const ColorBaseTeal300 = "#5eead4";
export const ColorBaseTeal400 = "#2dd4bf";
export const ColorBaseTeal500 = "#14b8a6";
export const ColorBaseTeal600 = "#0d9488";
export const ColorBaseTeal700 = "#0f766e";
export const ColorBaseTeal800 = "#115e59";
export const ColorBaseTeal900 = "#134e4a";
export const ColorBaseTeal950 = "#042f2e";
export const ColorBaseIndigo50 = "#eef2ff";
export const ColorBaseIndigo100 = "#e0e7ff";
export const ColorBaseIndigo200 = "#c7d2fe";
export const ColorBaseIndigo300 = "#a5b4fc";
export const ColorBaseIndigo400 = "#818cf8";
export const ColorBaseIndigo500 = "#6366f1";
export const ColorBaseIndigo600 = "#4f46e5";
export const ColorBaseIndigo700 = "#4338ca";
export const ColorBaseIndigo800 = "#3730a3";
export const ColorBaseIndigo900 = "#312e81";
export const ColorBaseIndigo950 = "#1e1b4b";
export const ColorBaseBlue50 = "#eff6ff";
export const ColorBaseBlue100 = "#dbeafe";
export const ColorBaseBlue200 = "#bfdbfe";
export const ColorBaseBlue300 = "#93c5fd";
export const ColorBaseBlue400 = "#60a5fa";
export const ColorBaseBlue500 = "#3b82f6";
export const ColorBaseBlue600 = "#2563eb";
export const ColorBaseBlue700 = "#1d4ed8";
export const ColorBaseBlue800 = "#1e40af";
export const ColorBaseBlue900 = "#1e3a8a";
export const ColorBaseBlue950 = "#172554";
export const ColorBaseEmerald50 = "#ecfdf5";
export const ColorBaseEmerald100 = "#d1fae5";
export const ColorBaseEmerald200 = "#a7f3d0";
export const ColorBaseEmerald300 = "#6ee7b7";
export const ColorBaseEmerald400 = "#34d399";
export const ColorBaseEmerald500 = "#10b981";
export const ColorBaseEmerald600 = "#059669";
export const ColorBaseEmerald700 = "#047857";
export const ColorBaseEmerald800 = "#065f46";
export const ColorBaseEmerald900 = "#064e3b";
export const ColorBaseEmerald950 = "#022c22";
export const ColorBaseAmber50 = "#fffbeb";
export const ColorBaseAmber100 = "#fef3c7";
export const ColorBaseAmber200 = "#fde68a";
export const ColorBaseAmber300 = "#fcd34d";
export const ColorBaseAmber400 = "#fbbf24";
export const ColorBaseAmber500 = "#f59e0b";
export const ColorBaseAmber600 = "#d97706";
export const ColorBaseAmber700 = "#b45309";
export const ColorBaseAmber800 = "#92400e";
export const ColorBaseAmber900 = "#78350f";
export const ColorBaseAmber950 = "#451a03";
export const ColorBaseRed50 = "#fef2f2";
export const ColorBaseRed100 = "#fee2e2";
export const ColorBaseRed200 = "#fecaca";
export const ColorBaseRed300 = "#fca5a5";
export const ColorBaseRed400 = "#f87171";
export const ColorBaseRed500 = "#ef4444";
export const ColorBaseRed600 = "#dc2626";
export const ColorBaseRed700 = "#b91c1c";
export const ColorBaseRed800 = "#991b1b";
export const ColorBaseRed900 = "#7f1d1d";
export const ColorBaseRed950 = "#450a0a";
export const ColorBaseYellow50 = "#fefce8";
export const ColorBaseYellow100 = "#fef9c3";
export const ColorBaseYellow200 = "#fef08a";
export const ColorBaseYellow300 = "#fde047";
export const ColorBaseYellow400 = "#facc15";
export const ColorBaseYellow500 = "#eab308";
export const ColorBaseYellow600 = "#ca8a04";
export const ColorBaseYellow700 = "#a16207";
export const ColorBaseYellow800 = "#854d0e";
export const ColorBaseYellow900 = "#713f12";
export const ColorBaseYellow950 = "#422006";
export const ColorBaseGreen50 = "#f0fdf4";
export const ColorBaseGreen100 = "#dcfce7";
export const ColorBaseGreen200 = "#bbf7d0";
export const ColorBaseGreen300 = "#86efac";
export const ColorBaseGreen400 = "#4ade80";
export const ColorBaseGreen500 = "#22c55e";
export const ColorBaseGreen600 = "#16a34a";
export const ColorBaseGreen700 = "#15803d";
export const ColorBaseGreen800 = "#166534";
export const ColorBaseGreen900 = "#14532d";
export const ColorBaseGreen950 = "#052e16";
export const ColorPrimary150 = "#f0f9ff";
export const ColorPrimary1100 = "#e0f2fe";
export const ColorPrimary1200 = "#bae6fd";
export const ColorPrimary1300 = "#7dd3fc";
export const ColorPrimary1400 = "#38bdf8";
export const ColorPrimary1500 = "#0ea5e9";
export const ColorPrimary1600 = "#0284c7";
export const ColorPrimary1700 = "#0369a1";
export const ColorPrimary1800 = "#075985";
export const ColorPrimary1900 = "#0c4a6e";
export const ColorPrimary1950 = "#082f49";
export const ColorPrimary250 = "#eef2ff";
export const ColorPrimary2100 = "#e0e7ff";
export const ColorPrimary2200 = "#c7d2fe";
export const ColorPrimary2300 = "#a5b4fc";
export const ColorPrimary2400 = "#818cf8";
export const ColorPrimary2500 = "#6366f1";
export const ColorPrimary2600 = "#4f46e5";
export const ColorPrimary2700 = "#4338ca";
export const ColorPrimary2800 = "#3730a3";
export const ColorPrimary2900 = "#312e81";
export const ColorPrimary2950 = "#1e1b4b";
export const ColorSecondary150 = "#f8fafc";
export const ColorSecondary1100 = "#f1f5f9";
export const ColorSecondary1200 = "#e2e8f0";
export const ColorSecondary1300 = "#cbd5e1";
export const ColorSecondary1400 = "#94a3b8";
export const ColorSecondary1500 = "#64748b";
export const ColorSecondary1600 = "#475569";
export const ColorSecondary1700 = "#334155";
export const ColorSecondary1800 = "#1e293b";
export const ColorSecondary1900 = "#0f172a";
export const ColorSecondary1950 = "#020617";
export const ColorSecondary250 = "#fafaf9";
export const ColorSecondary2100 = "#f5f5f4";
export const ColorSecondary2200 = "#e7e5e4";
export const ColorSecondary2300 = "#d6d3d1";
export const ColorSecondary2400 = "#a8a29e";
export const ColorSecondary2500 = "#78716c";
export const ColorSecondary2600 = "#57534e";
export const ColorSecondary2700 = "#44403c";
export const ColorSecondary2800 = "#292524";
export const ColorSecondary2900 = "#1c1917";
export const ColorSecondary2950 = "#0c0a09";
export const ColorAccent150 = "#ecfdf5";
export const ColorAccent1100 = "#d1fae5";
export const ColorAccent1200 = "#a7f3d0";
export const ColorAccent1300 = "#6ee7b7";
export const ColorAccent1400 = "#34d399";
export const ColorAccent1500 = "#10b981";
export const ColorAccent1600 = "#059669";
export const ColorAccent1700 = "#047857";
export const ColorAccent1800 = "#065f46";
export const ColorAccent1900 = "#064e3b";
export const ColorAccent1950 = "#022c22";
export const ColorAccent250 = "#fffbeb";
export const ColorAccent2100 = "#fef3c7";
export const ColorAccent2200 = "#fde68a";
export const ColorAccent2300 = "#fcd34d";
export const ColorAccent2400 = "#fbbf24";
export const ColorAccent2500 = "#f59e0b";
export const ColorAccent2600 = "#d97706";
export const ColorAccent2700 = "#b45309";
export const ColorAccent2800 = "#92400e";
export const ColorAccent2900 = "#78350f";
export const ColorAccent2950 = "#451a03";
export const ColorAccent350 = "#fef2f2";
export const ColorAccent3100 = "#fee2e2";
export const ColorAccent3200 = "#fecaca";
export const ColorAccent3300 = "#fca5a5";
export const ColorAccent3400 = "#f87171";
export const ColorAccent3500 = "#ef4444";
export const ColorAccent3600 = "#dc2626";
export const ColorAccent3700 = "#b91c1c";
export const ColorAccent3800 = "#991b1b";
export const ColorAccent3900 = "#7f1d1d";
export const ColorAccent3950 = "#450a0a";
export const ColorAccent450 = "#eff6ff";
export const ColorAccent4100 = "#dbeafe";
export const ColorAccent4200 = "#bfdbfe";
export const ColorAccent4300 = "#93c5fd";
export const ColorAccent4400 = "#60a5fa";
export const ColorAccent4500 = "#3b82f6";
export const ColorAccent4600 = "#2563eb";
export const ColorAccent4700 = "#1d4ed8";
export const ColorAccent4800 = "#1e40af";
export const ColorAccent4900 = "#1e3a8a";
export const ColorAccent4950 = "#172554";
export const ColorAccent550 = "#f0fdfa";
export const ColorAccent5100 = "#ccfbf1";
export const ColorAccent5200 = "#99f6e4";
export const ColorAccent5300 = "#5eead4";
export const ColorAccent5400 = "#2dd4bf";
export const ColorAccent5500 = "#14b8a6";
export const ColorAccent5600 = "#0d9488";
export const ColorAccent5700 = "#0f766e";
export const ColorAccent5800 = "#115e59";
export const ColorAccent5900 = "#134e4a";
export const ColorAccent5950 = "#042f2e";
export const ColorNeutral10 = "#ffffff";
export const ColorNeutral150 = "#f8fafc";
export const ColorNeutral1100 = "#f1f5f9";
export const ColorNeutral1200 = "#e2e8f0";
export const ColorNeutral1300 = "#cbd5e1";
export const ColorNeutral1400 = "#94a3b8";
export const ColorNeutral1500 = "#64748b";
export const ColorNeutral1600 = "#475569";
export const ColorNeutral1700 = "#334155";
export const ColorNeutral1800 = "#1e293b";
export const ColorNeutral1900 = "#0f172a";
export const ColorNeutral1950 = "#020617";
export const ColorNeutral11000 = "#000000";
export const ColorNeutral250 = "#fafafa";
export const ColorNeutral2100 = "#f4f4f5";
export const ColorNeutral2200 = "#e4e4e7";
export const ColorNeutral2300 = "#d4d4d8";
export const ColorNeutral2400 = "#a1a1aa";
export const ColorNeutral2500 = "#71717a";
export const ColorNeutral2600 = "#52525b";
export const ColorNeutral2700 = "#3f3f46";
export const ColorNeutral2800 = "#27272a";
export const ColorNeutral2900 = "#18181b";
export const ColorNeutral2950 = "#09090b";
export const ColorNeutralOverlay = "#00000080";
export const ColorBgPaper = "#ffffff";
export const ColorBgBase = "#f8fafc";
export const ColorBgSurface = "#f1f5f9";
export const ColorBgElevated = "#f8fafc";
export const ColorBgPrimary = "#0ea5e9";
export const ColorBgPrimaryHover = "#0284c7";
export const ColorBgPrimaryActive = "#0369a1";
export const ColorBgPrimarySubtle = "#f0f9ff";
export const ColorBgPrimaryMuted = "#e0f2fe";
export const ColorBgSurfaceHover = "#e2e8f0";
export const ColorBgSurfaceActive = "#cbd5e1";
export const ColorBgSecondary = "#64748b"; // Secondary bg (consolidated from secondary.1 = neutral.1)
export const ColorBgSecondaryHover = "#475569";
export const ColorBgSuccessSubtle = "#ecfdf5"; // Subtle success bg (alerts, toasts)
export const ColorBgSuccess = "#d1fae5"; // Default success bg (badges, banners)
export const ColorBgSuccessSolid = "#10b981"; // Solid success bg (filled indicators)
export const ColorBgWarningSubtle = "#fffbeb";
export const ColorBgWarning = "#fef3c7";
export const ColorBgWarningSolid = "#f59e0b";
export const ColorBgErrorSubtle = "#fef2f2";
export const ColorBgError = "#fee2e2";
export const ColorBgErrorSolid = "#ef4444";
export const ColorBgInfoSubtle = "#eff6ff";
export const ColorBgInfo = "#dbeafe";
export const ColorBgInfoSolid = "#3b82f6";
export const ColorBgOverlay = "#00000080"; // Modal/dialog backdrop
export const ColorBgInverse = "#0f172a"; // Dark/inverted background (code blocks)
export const ColorBgInverseHover = "#334155"; // Hover on inverted background
export const ColorTextBase = "#0f172a";
export const ColorTextHeading = "#0f172a";
export const ColorTextMuted = "#475569";
export const ColorTextDisabled = "#94a3b8";
export const ColorTextInverse = "#f8fafc";
export const ColorTextOnPrimary = "#ffffff";
export const ColorTextPrimary = "#0284c7";
export const ColorTextSuccess = "#047857";
export const ColorTextWarning = "#b45309";
export const ColorTextError = "#b91c1c";
export const ColorTextInfo = "#1d4ed8";
export const ColorBorderDefault = "#cbd5e1";
export const ColorBorderMuted = "#e2e8f0";
export const ColorBorderStrong = "#94a3b8";
export const ColorBorderFocus = "#0ea5e9";
export const ColorBorderSuccess = "#10b981";
export const ColorBorderWarning = "#f59e0b";
export const ColorBorderError = "#ef4444";
export const ColorBorderInfo = "#3b82f6";
export const ColorInteractivePrimary = "#0ea5e9";
export const ColorInteractivePrimaryHover = "#0284c7";
export const ColorInteractivePrimaryActive = "#0369a1";
export const ColorInteractivePrimaryDisabled = "#cbd5e1";
export const ColorInteractiveSecondary = "#64748b"; // Consolidated from secondary.1 = neutral.1
export const ColorInteractiveSecondaryHover = "#475569";
export const ColorInteractiveSecondaryActive = "#334155";
export const ColorAccordionBg = "#ffffff"; // Item background
export const ColorAccordionBorder = "#e2e8f0"; // Item border/divider
export const ColorAccordionTriggerText = "#0f172a"; // Trigger text
export const ColorAccordionTriggerHoverBg = "#f1f5f9"; // Trigger hover background
export const ColorAccordionContentText = "#0f172a"; // Content text
export const ColorAccordionIcon = "#475569"; // Chevron icon color
export const ColorAlertTitle = "#0f172a"; // Alert title text
export const ColorAlertDescription = "#0f172a"; // Alert description text
export const ColorAlertInfoBg = "#eff6ff"; // Info variant background
export const ColorAlertInfoBorder = "#3b82f6"; // Info left accent border
export const ColorAlertInfoIcon = "#1d4ed8"; // Info icon color
export const ColorAlertSuccessBg = "#ecfdf5"; // Success variant background
export const ColorAlertSuccessBorder = "#10b981"; // Success left accent border
export const ColorAlertSuccessIcon = "#047857"; // Success icon color
export const ColorAlertWarningBg = "#fffbeb"; // Warning variant background
export const ColorAlertWarningBorder = "#f59e0b"; // Warning left accent border
export const ColorAlertWarningIcon = "#b45309"; // Warning icon color
export const ColorAlertErrorBg = "#fef2f2"; // Error variant background
export const ColorAlertErrorBorder = "#ef4444"; // Error left accent border
export const ColorAlertErrorIcon = "#b91c1c"; // Error icon color
export const ColorAlertdlgOverlay = "#00000080"; // AlertDialog backdrop overlay
export const ColorAlertdlgBg = "#ffffff"; // AlertDialog content background
export const ColorAlertdlgTitle = "#0f172a"; // AlertDialog title text
export const ColorAlertdlgDescription = "#475569"; // AlertDialog description text
export const ColorAlertdlgBorder = "#e2e8f0"; // AlertDialog border
export const ColorAlertdlgActionBg = "#fee2e2"; // Destructive action button background
export const ColorAlertdlgActionText = "#f8fafc"; // Destructive action button text
export const ColorAlertdlgActionHoverBg = "#b91c1c"; // Destructive action button hover
export const ColorAlertdlgCancelBg = "#f1f5f9"; // Cancel button background
export const ColorAlertdlgCancelText = "#0f172a"; // Cancel button text
export const ColorAlertdlgCancelHoverBg = "#e2e8f0"; // Cancel button hover
export const ColorAvatarBg = "#f1f5f9"; // Avatar fallback background
export const ColorAvatarText = "#475569"; // Avatar fallback text
export const ColorAvatarBorder = "#cbd5e1"; // Avatar border
export const ColorBadgeSuccessBg = "#d1fae5";
export const ColorBadgeSuccessText = "#047857";
export const ColorBadgeSuccessBorder = "#10b981";
export const ColorBadgeWarningBg = "#fef3c7";
export const ColorBadgeWarningText = "#b45309";
export const ColorBadgeWarningBorder = "#f59e0b";
export const ColorBadgeErrorBg = "#fee2e2";
export const ColorBadgeErrorText = "#b91c1c";
export const ColorBadgeErrorBorder = "#ef4444";
export const ColorBadgeInfoBg = "#dbeafe";
export const ColorBadgeInfoText = "#1d4ed8";
export const ColorBadgeInfoBorder = "#3b82f6";
export const ColorBadgeNeutralBg = "#f1f5f9";
export const ColorBadgeNeutralText = "#475569";
export const ColorBadgeNeutralBorder = "#e2e8f0";
export const ColorBannerInfoBg = "#dbeafe"; // Info background
export const ColorBannerInfoText = "#1d4ed8"; // Info text
export const ColorBannerInfoBorder = "#3b82f6"; // Info border
export const ColorBannerSuccessBg = "#d1fae5"; // Success background
export const ColorBannerSuccessText = "#047857"; // Success text
export const ColorBannerSuccessBorder = "#10b981"; // Success border
export const ColorBannerWarningBg = "#fef3c7"; // Warning background
export const ColorBannerWarningText = "#b45309"; // Warning text
export const ColorBannerWarningBorder = "#f59e0b"; // Warning border
export const ColorBannerErrorBg = "#fee2e2"; // Error background
export const ColorBannerErrorText = "#b91c1c"; // Error text
export const ColorBannerErrorBorder = "#ef4444"; // Error border
export const ColorBannerDismiss = "#475569"; // Dismiss icon color
export const ColorBqBorder = "#94a3b8"; // Left accent border
export const ColorBqBg = "#f1f5f9"; // Background
export const ColorBqText = "#0f172a"; // Quote text
export const ColorBqCiteText = "#475569"; // Citation/author text
export const ColorBreadcrumbsText = "#475569"; // Breadcrumb link text
export const ColorBreadcrumbsTextCurrent = "#0f172a"; // Current breadcrumb text
export const ColorBreadcrumbsSeparator = "#94a3b8"; // Breadcrumb separator color
export const ColorBreadcrumbsHoverText = "#0284c7"; // Breadcrumb link hover text
export const ColorBtnPrimaryBg = "#0ea5e9";
export const ColorBtnPrimaryBgHover = "#0284c7";
export const ColorBtnPrimaryBgActive = "#0369a1";
export const ColorBtnPrimaryText = "#f8fafc";
export const ColorBtnPrimaryBorder = "#0ea5e9";
export const ColorBtnSecondaryBg = "#f1f5f9";
export const ColorBtnSecondaryBgHover = "#e2e8f0";
export const ColorBtnSecondaryBgActive = "#cbd5e1";
export const ColorBtnSecondaryText = "#0f172a";
export const ColorBtnSecondaryBorder = "#cbd5e1";
export const ColorBtnGhostBgHover = "#f1f5f9";
export const ColorBtnGhostBgActive = "#e2e8f0";
export const ColorBtnGhostText = "#0284c7";
export const ColorBtnDisabledBg = "#cbd5e1";
export const ColorBtnDisabledText = "#94a3b8";
export const ColorCardBg = "#ffffff"; // White paper background
export const ColorCardBorder = "#e2e8f0";
export const ColorChart1 = "#0ea5e9"; // Chart color 1 (primary blue)
export const ColorChart2 = "#047857"; // Chart color 2 (green)
export const ColorChart3 = "#b45309"; // Chart color 3 (amber)
export const ColorChart4 = "#b91c1c"; // Chart color 4 (red)
export const ColorChart5 = "#1d4ed8"; // Chart color 5 (info blue)
export const ColorChartGrid = "#e2e8f0"; // Chart grid line color
export const ColorChartAxis = "#475569"; // Chart axis text color
export const ColorChartTooltipBg = "#ffffff"; // Chart tooltip background
export const ColorChartTooltipBorder = "#e2e8f0"; // Chart tooltip border
export const ColorChartTooltipText = "#0f172a"; // Chart tooltip text
export const ColorCheckboxBg = "#ffffff"; // Unchecked background (white)
export const ColorCheckboxBorder = "#cbd5e1"; // Unchecked border
export const ColorCheckboxBorderHover = "#94a3b8"; // Hover border
export const ColorCheckboxCheckedBg = "#0ea5e9"; // Sky blue checked bg
export const ColorCheckboxCheckedBorder = "#0ea5e9"; // Sky blue checked border
export const ColorCheckboxCheckedIcon = "#ffffff"; // White check icon
export const ColorCheckboxFocusRing = "#0ea5e9"; // Sky blue focus ring
export const ColorCheckboxDisabledBg = "#f1f5f9"; // Disabled background
export const ColorCheckboxLabel = "#0f172a"; // Label text color
export const ColorCheckboxDescription = "#475569"; // Description text color
export const ColorCodeBg = "#f1f5f9"; // Inline code background
export const ColorCodeText = "#0284c7"; // Inline code text
export const ColorCodeBlockBg = "#0f172a"; // Code block dark background
export const ColorCodeBlockText = "#f8fafc"; // Code block text on dark bg
export const ColorCodeCopyHoverBg = "#334155"; // Copy button hover on dark bg
export const ColorCodeLineNumber = "#475569"; // Line number text color
export const ColorCmbTriggerBg = "#ffffff"; // Trigger background (matches Input)
export const ColorCmbTriggerBorder = "#cbd5e1"; // Trigger border
export const ColorCmbTriggerText = "#0f172a"; // Trigger text
export const ColorCmbTriggerPlaceholder = "#475569"; // Placeholder text
export const ColorCmbContentBg = "#ffffff"; // Dropdown background
export const ColorCmbContentBorder = "#e2e8f0"; // Dropdown border (subtle)
export const ColorCmbItemHoverBg = "#e2e8f0"; // Item hover
export const ColorCmbItemSelectedBg = "#f0f9ff"; // Selected item background
export const ColorCmbItemSelectedText = "#0284c7"; // Selected item text
export const ColorCmbSearchBg = "#ffffff"; // Search input background
export const ColorCmbEmptyText = "#475569"; // No results text
export const ColorCommandBg = "#ffffff"; // Command palette background
export const ColorCommandBorder = "#e2e8f0"; // Command palette border
export const ColorCommandInputText = "#0f172a"; // Command input text
export const ColorCommandInputPlaceholder = "#94a3b8"; // Command input placeholder
export const ColorCommandItemText = "#0f172a"; // Command item text
export const ColorCommandItemHoverBg = "#f1f5f9"; // Command item hover background
export const ColorCommandGroupHeading = "#475569"; // Command group heading text
export const ColorCommandSeparator = "#e2e8f0"; // Command separator color
export const ColorCommandEmptyText = "#475569"; // Command empty state text
export const ColorCpybtnBg = "#f1f5f9"; // Default background
export const ColorCpybtnBgHover = "#e2e8f0"; // Hover background
export const ColorCpybtnIcon = "#475569"; // Copy icon color
export const ColorCpybtnIconCopied = "#047857"; // Check icon after copy
export const ColorCpybtnBorder = "#cbd5e1"; // Button border
export const ColorDatatableToolbarBg = "#ffffff"; // Toolbar background
export const ColorDatatableRowSelectedBg = "#f1f5f9"; // Selected row background
export const ColorDatatableSortIcon = "#475569"; // Sort icon inactive
export const ColorDatatableSortIconActive = "#0ea5e9"; // Sort icon active
export const ColorDatatableEmptyText = "#475569"; // Empty state text
export const ColorDatepickerPopoverBg = "#ffffff"; // White popover background
export const ColorDatepickerPopoverBorder = "#e2e8f0"; // Subtle popover border
export const ColorDatepickerHeaderText = "#0f172a"; // Month/year header text
export const ColorDatepickerWeekdayText = "#475569"; // Mo Di Mi weekday labels
export const ColorDatepickerDayText = "#0f172a"; // Default day number
export const ColorDatepickerDayHoverBg = "#f1f5f9"; // Day hover background
export const ColorDatepickerDaySelectedBg = "#0ea5e9"; // Sky Blue selected day
export const ColorDatepickerDaySelectedText = "#f8fafc"; // White text on selected
export const ColorDatepickerDayTodayBorder = "#0ea5e9"; // Sky Blue ring for today
export const ColorDatepickerDayDisabledText = "#94a3b8"; // Disabled/outside day
export const ColorDatepickerDayRangeBg = "#e0f2fe"; // Subtle sky-100 for range middle days
export const ColorDatepickerNavHoverBg = "#f1f5f9"; // Chevron hover bg
export const ColorDialogOverlay = "#00000080"; // Dialog backdrop overlay
export const ColorDialogBg = "#ffffff"; // Dialog content background
export const ColorDialogTitle = "#0f172a"; // Dialog title text
export const ColorDialogDescription = "#475569"; // Dialog description text
export const ColorDialogBorder = "#e2e8f0"; // Dialog border
export const ColorDrawerOverlay = "#00000080"; // Drawer backdrop overlay
export const ColorDrawerBg = "#ffffff"; // Drawer content background
export const ColorDrawerTitle = "#0f172a"; // Drawer title text
export const ColorDrawerDescription = "#475569"; // Drawer description text
export const ColorDrawerBorder = "#e2e8f0"; // Drawer top border
export const ColorDrawerHandle = "#94a3b8"; // Drag handle bar color
export const ColorDropdownBg = "#ffffff"; // Menu background
export const ColorDropdownBorder = "#e2e8f0"; // Menu border
export const ColorDropdownItemText = "#0f172a"; // Item text
export const ColorDropdownItemHoverBg = "#f1f5f9"; // Item hover/focus background
export const ColorDropdownItemDisabledText = "#94a3b8"; // Disabled item text
export const ColorDropdownItemIcon = "#475569"; // Item icon color
export const ColorDropdownDestructiveText = "#b91c1c"; // Destructive item text (red)
export const ColorDropdownDestructiveHoverBg = "#fef2f2"; // Destructive item hover bg
export const ColorDropdownSeparator = "#e2e8f0"; // Separator line
export const ColorDropdownLabelText = "#475569"; // Group label text
export const ColorEmptystateIcon = "#475569"; // Default icon color (muted)
export const ColorEmptystateIconError = "#b91c1c"; // Error variant icon color
export const ColorEmptystateIconSuccess = "#047857"; // Success variant icon color
export const ColorEmptystateTitle = "#0f172a"; // Title text color
export const ColorEmptystateDescription = "#475569"; // Description text color (muted)
export const ColorFileuploadZoneBg = "#f1f5f9"; // Upload zone background (slate-100) – visible against white page
export const ColorFileuploadZoneBorder = "#cbd5e1"; // Dashed border – gray-300 for visibility
export const ColorFileuploadZoneText = "#0f172a"; // Zone primary instruction text
export const ColorFileuploadZoneTextSub = "#475569"; // Zone secondary/sub text
export const ColorFileuploadZoneIcon = "#0ea5e9"; // Upload cloud icon – sky-500 brand color
export const ColorFileuploadHoverBg = "#f0f9ff"; // Sky-50 hover bg
export const ColorFileuploadHoverBorder = "#0ea5e9"; // Sky-500 solid hover border
export const ColorFileuploadDragBg = "#f0f9ff"; // Sky-50 drag-over bg
export const ColorFileuploadDragBorder = "#0ea5e9"; // Sky-500 drag-over border
export const ColorFileuploadDragIcon = "#0ea5e9"; // Sky-500 drag-over icon
export const ColorFileuploadDragText = "#0284c7"; // Sky-600 drag-over text
export const ColorFileuploadFileText = "#0f172a"; // File name text
export const ColorFileuploadFileSize = "#475569"; // File size text
export const ColorFileuploadFileIcon = "#475569"; // File type icon
export const ColorFileuploadFileRemove = "#475569"; // Remove button
export const ColorFileuploadFileRemoveHover = "#b91c1c"; // Remove hover
export const ColorFileuploadProgressBg = "#e2e8f0"; // Progress track
export const ColorFileuploadProgressFill = "#0ea5e9"; // Sky-500 progress bar
export const ColorFileuploadErrorText = "#b91c1c"; // Error message
export const ColorFileuploadErrorBorder = "#ef4444"; // Error zone border
export const ColorHlBg = "#fef3c7"; // Highlight background (yellow)
export const ColorHlText = "#0f172a"; // Highlight text
export const ColorHovercardBg = "#ffffff"; // HoverCard background
export const ColorHovercardBorder = "#e2e8f0"; // HoverCard border
export const ColorIconDefault = "#0f172a"; // Default icon stroke color (currentColor)
export const ColorIconMuted = "#475569"; // Muted/secondary icon color
export const ColorImgBg = "#f1f5f9"; // Loading placeholder background
export const ColorImgFallbackBg = "#e2e8f0"; // Error fallback background
export const ColorImgFallbackText = "#475569"; // Error fallback icon/text
export const ColorImgBorder = "#e2e8f0"; // Optional border
export const ColorInputBg = "#ffffff"; // White paper background
export const ColorInputBgDisabled = "#f1f5f9";
export const ColorInputText = "#0f172a";
export const ColorInputTextPlaceholder = "#475569";
export const ColorInputBorder = "#cbd5e1";
export const ColorInputBorderHover = "#94a3b8";
export const ColorInputBorderFocus = "#0ea5e9";
export const ColorInputBorderError = "#ef4444";
export const ColorInputotpBg = "#ffffff"; // Slot background
export const ColorInputotpBgDisabled = "#f1f5f9"; // Disabled slot background
export const ColorInputotpText = "#0f172a"; // Digit text color
export const ColorInputotpBorder = "#cbd5e1"; // Slot border
export const ColorInputotpBorderFocus = "#0ea5e9"; // Active slot focus ring
export const ColorInputotpBorderError = "#ef4444"; // Error state border
export const ColorInputotpCaret = "#0ea5e9"; // Blinking caret color
export const ColorInputotpSeparator = "#475569"; // Group separator color
export const ColorKbdBg = "#ffffff"; // Key background
export const ColorKbdText = "#0f172a"; // Key text
export const ColorKbdBorder = "#e2e8f0"; // Key border
export const ColorLinkText = "#0ea5e9"; // Default link text color
export const ColorLinkTextHover = "#0284c7"; // Link hover text color
export const ColorLdovlBg = "#00000080"; // Overlay background (semi-transparent)
export const ColorLdovlText = "#0f172a"; // Loading text color
export const ColorLdovlSpinner = "#0ea5e9"; // Spinner color
export const ColorMenubarBg = "#ffffff"; // Menubar background
export const ColorMenubarBorder = "#e2e8f0"; // Menubar border
export const ColorMenubarTriggerText = "#0f172a"; // Trigger text
export const ColorMenubarTriggerHoverBg = "#f1f5f9"; // Trigger hover background
export const ColorMenubarTriggerActiveBg = "#f1f5f9"; // Trigger active/open background
export const ColorModalOverlay = "#00000080"; // Dark backdrop behind modal
export const ColorModalBg = "#ffffff"; // White content background
export const ColorModalTitle = "#0f172a"; // Modal title text
export const ColorModalDescription = "#475569"; // Modal description text
export const ColorModalDivider = "#e2e8f0"; // Header/footer border
export const ColorModalCloseHoverBg = "#f1f5f9"; // Close button hover bg
export const ColorModalCloseHoverText = "#0ea5e9"; // Close button hover color (sky blue)
export const ColorNavText = "#0f172a"; // Navigation item text
export const ColorNavHoverBg = "#f1f5f9"; // Item hover background
export const ColorNavActiveBg = "#f1f5f9"; // Active item background
export const ColorNavDropdownBg = "#ffffff"; // Dropdown panel background
export const ColorNavDropdownBorder = "#e2e8f0"; // Dropdown panel border
export const ColorNavFocusRing = "#0ea5e9"; // Focus ring color
export const ColorNumberinputBg = "#ffffff"; // Input background
export const ColorNumberinputBgDisabled = "#f1f5f9"; // Disabled background
export const ColorNumberinputText = "#0f172a"; // Input value text
export const ColorNumberinputBorder = "#cbd5e1"; // Default border
export const ColorNumberinputBorderHover = "#94a3b8"; // Hover border
export const ColorNumberinputBorderFocus = "#0ea5e9"; // Focus ring color
export const ColorNumberinputBorderError = "#ef4444"; // Error border
export const ColorNumberinputStepperText = "#475569"; // Stepper button icon color
export const ColorNumberinputStepperTextHover = "#0f172a"; // Stepper button icon hover color
export const ColorNumberinputStepperBgHover = "#f1f5f9"; // Stepper button hover background
export const ColorPaginationItemBg = "#ffffff"; // Page button background
export const ColorPaginationItemBorder = "#cbd5e1"; // Page button border
export const ColorPaginationItemText = "#0f172a"; // Page button text
export const ColorPaginationItemHoverBg = "#f1f5f9"; // Page button hover background
export const ColorPaginationItemActiveBg = "#0ea5e9"; // Active page background (Sky Blue)
export const ColorPaginationItemActiveText = "#ffffff"; // Active page text (white)
export const ColorPaginationItemActiveBorder = "#0ea5e9"; // Active page border (Sky Blue)
export const ColorPwinputToggle = "#475569"; // Toggle icon color
export const ColorPwinputToggleHover = "#0f172a"; // Toggle icon hover
export const ColorPwinputStrengthWeak = "#b91c1c"; // Strength: weak
export const ColorPwinputStrengthMedium = "#b45309"; // Strength: medium
export const ColorPwinputStrengthStrong = "#047857"; // Strength: strong
export const ColorPopoverBg = "#ffffff"; // White popover background
export const ColorPopoverBorder = "#e2e8f0"; // Subtle outer border
export const ColorProgressTrack = "#f1f5f9";
export const ColorProgressFill = "#0ea5e9";
export const ColorProgressFillSuccess = "#10b981";
export const ColorProgressFillWarning = "#f59e0b";
export const ColorProgressFillError = "#ef4444";
export const ColorProgressLabel = "#0f172a";
export const ColorProgressValue = "#475569";
export const ColorRadioBg = "#ffffff"; // Unchecked background (white)
export const ColorRadioBorder = "#cbd5e1"; // Unchecked border
export const ColorRadioBorderHover = "#94a3b8"; // Hover border
export const ColorRadioSelectedBorder = "#0ea5e9"; // Sky blue selected border
export const ColorRadioSelectedDot = "#0ea5e9"; // Sky blue inner dot
export const ColorRadioFocusRing = "#0ea5e9"; // Sky blue focus ring
export const ColorRadioDisabledBg = "#f1f5f9"; // Disabled background
export const ColorRadioItemHoverBg = "#f1f5f9"; // Row hover background
export const ColorRadioLabel = "#0f172a"; // Label text color
export const ColorRadioDescription = "#475569"; // Description text color
export const ColorRtgFilled = "#b45309"; // Filled star (gold/amber)
export const ColorRtgEmpty = "#94a3b8"; // Empty star
export const ColorRtgHover = "#f59e0b"; // Hover color
export const ColorRtgText = "#475569"; // Optional rating text
export const ColorRszHandleBg = "#e2e8f0"; // Handle default background
export const ColorRszHandleHoverBg = "#0ea5e9"; // Handle hover/active
export const ColorRszHandleBorder = "#cbd5e1"; // Handle grip border
export const ColorRszPanelBorder = "#e2e8f0"; // Panel divider border
export const ColorScrollareaThumb = "#cbd5e1"; // Scrollbar thumb color
export const ColorScrollareaThumbHover = "#94a3b8"; // Scrollbar thumb hover color
export const ColorScrollareaTrack = "#00000000"; // Scrollbar track background
export const ColorSinputIcon = "#475569"; // Search icon color
export const ColorSinputIconFocus = "#0f172a"; // Search icon on focus
export const ColorSinputClear = "#475569"; // Clear button color
export const ColorSinputClearHover = "#0f172a"; // Clear button hover
export const ColorSelectTriggerBg = "#ffffff"; // White trigger background (matches Input)
export const ColorSelectTriggerText = "#0f172a"; // Trigger text color
export const ColorSelectTriggerPlaceholder = "#475569"; // Placeholder text
export const ColorSelectTriggerBorder = "#cbd5e1"; // Default border
export const ColorSelectTriggerBorderHover = "#94a3b8"; // Hover border
export const ColorSelectTriggerBorderFocus = "#0ea5e9"; // Focus border (sky)
export const ColorSelectTriggerBorderError = "#ef4444"; // Error border
export const ColorSelectTriggerDisabledBg = "#f1f5f9"; // Disabled background
export const ColorSelectIcon = "#475569"; // Chevron/search icon color
export const ColorSelectIconHover = "#0f172a"; // Icon hover color
export const ColorSelectPopoverBg = "#ffffff"; // White dropdown background
export const ColorSelectPopoverBorder = "#e2e8f0"; // Dropdown border
export const ColorSelectItemText = "#0f172a"; // Option text
export const ColorSelectItemHoverBg = "#f1f5f9"; // Option hover/focus bg
export const ColorSelectItemSelectedBg = "#f0f9ff"; // Selected option background
export const ColorSelectItemSelectedText = "#0284c7"; // Selected option text (sky)
export const ColorSelectItemDisabledText = "#94a3b8"; // Disabled option text
export const ColorSelectCheckIcon = "#0ea5e9"; // Checkmark icon color (sky)
export const ColorSelectGroupLabel = "#475569"; // Option group label
export const ColorSelectSeparator = "#e2e8f0"; // Separator line
export const ColorSelectSearchBg = "#f8fafc"; // Combobox search input bg
export const ColorSelectEmptyText = "#475569"; // No results text
export const ColorSelectCheckboxText = "#ffffff"; // Checkbox checked text (white)
export const ColorSelectCheckboxBg = "#ffffff"; // Checkbox unchecked background
export const ColorSeparator = "#e2e8f0"; // Separator line color
export const ColorSessionCardBg = "#ffffff"; // Card background
export const ColorSessionCardBorder = "#e2e8f0"; // Default border
export const ColorSessionCardBorderHover = "#cbd5e1"; // Hover border
export const ColorSessionCardBgHover = "#f1f5f9"; // Hover background
export const ColorSessionCardBgError = "#fef2f2"; // Error state background
export const ColorSessionCardBorderError = "#ef4444"; // Error state border
export const ColorSessionCardTextPrimary = "#0f172a"; // Title and value text
export const ColorSessionCardTextSecondary = "#475569"; // Date, labels, description
export const ColorSessionCardTextTertiary = "#94a3b8"; // Zone labels (Z1-Z5)
export const ColorSessionCardTextError = "#b91c1c"; // Error message text
export const ColorSessionCardSkeleton = "#f1f5f9"; // Skeleton placeholder
export const ColorSessionCardZoneBg = "#f1f5f9"; // Zone bar background
export const ColorSessionCardZone1 = "#94a3b8"; // HR Zone 1 Recovery
export const ColorSessionCardZone2 = "#10b981"; // HR Zone 2 Aerobic
export const ColorSessionCardZone3 = "#f59e0b"; // HR Zone 3 Tempo
export const ColorSessionCardZone4 = "#b45309"; // HR Zone 4 Threshold
export const ColorSessionCardZone5 = "#ef4444"; // HR Zone 5 Maximum
export const ColorSessionCardFocusRing = "#0ea5e9"; // Focus ring for interactive state
export const ColorSheetOverlay = "#00000080"; // Sheet backdrop overlay
export const ColorSheetBg = "#ffffff"; // Sheet panel background
export const ColorSheetBorder = "#e2e8f0"; // Sheet border
export const ColorSheetTitle = "#0f172a"; // Sheet title text
export const ColorSheetDescription = "#475569"; // Sheet description text
export const ColorSkeletonBase = "#f1f5f9";
export const ColorSkeletonShimmer = "#f8fafc";
export const ColorSliderTrack = "#f1f5f9"; // Slider track background
export const ColorSliderRange = "#0ea5e9"; // Slider filled range
export const ColorSliderThumb = "#ffffff"; // Slider thumb background
export const ColorSliderThumbBorder = "#0ea5e9"; // Slider thumb border
export const ColorSliderThumbHover = "#0284c7"; // Slider thumb hover border
export const ColorSpinnerPrimary = "#0ea5e9";
export const ColorSpinnerTrack = "#e2e8f0";
export const ColorSpinnerLabel = "#475569";
export const ColorStatCardBg = "#ffffff"; // Card background
export const ColorStatCardBorder = "#e2e8f0"; // Default border
export const ColorStatCardTextPrimary = "#0f172a"; // Main value text
export const ColorStatCardTextSecondary = "#475569"; // Title, unit, description
export const ColorStatCardBorderSuccess = "#10b981"; // Success variant left accent
export const ColorStatCardBorderWarning = "#f59e0b"; // Warning variant left accent
export const ColorStatCardBorderError = "#ef4444"; // Error variant left accent
export const ColorStatCardTrendUp = "#047857"; // Positive trend indicator
export const ColorStatCardTrendDown = "#b91c1c"; // Negative trend indicator
export const ColorStatCardTrendNeutral = "#475569"; // Neutral trend indicator
export const ColorSwitchTrackBg = "#cbd5e1"; // Unchecked track (gray-300)
export const ColorSwitchTrackBgChecked = "#0ea5e9"; // Checked track (sky blue)
export const ColorSwitchThumbBg = "#ffffff"; // White thumb
export const ColorSwitchFocusRing = "#0ea5e9"; // Sky blue focus ring
export const ColorSwitchDisabledTrackBg = "#f1f5f9"; // Disabled track
export const ColorSwitchLabel = "#0f172a"; // Label text color
export const ColorSwitchDescription = "#475569"; // Description text color
export const ColorTableHeaderBg = "#f8fafc";
export const ColorTableHeaderText = "#0f172a";
export const ColorTableBorder = "#e2e8f0";
export const ColorTableRowStripe = "#f8fafc";
export const ColorTableRowHover = "#f1f5f9";
export const ColorTabsListBg = "#f1f5f9"; // Pills variant list background
export const ColorTabsTriggerText = "#475569"; // Inactive tab text
export const ColorTabsTriggerTextActive = "#0ea5e9"; // Active tab text (sky)
export const ColorTabsTriggerTextHover = "#0f172a"; // Hovered tab text
export const ColorTabsTriggerBgActive = "#ffffff"; // Pills active tab background (white)
export const ColorTabsTriggerHoverBg = "#f1f5f9"; // Underline hover background
export const ColorTabsUnderline = "#0ea5e9"; // Active underline indicator (sky)
export const ColorTabsBorder = "#e2e8f0"; // Underline variant bottom border
export const ColorTabsContentText = "#0f172a"; // Tab content text
export const ColorTagBgDefault = "#f1f5f9"; // Default tag background
export const ColorTagBgSuccess = "#ecfdf5"; // Success variant background
export const ColorTagBgWarning = "#fffbeb"; // Warning variant background
export const ColorTagBgError = "#fef2f2"; // Error variant background
export const ColorTagBgInfo = "#eff6ff"; // Info variant background
export const ColorTagTextDefault = "#0f172a"; // Default tag text color
export const ColorTagTextSuccess = "#047857"; // Success variant text color
export const ColorTagTextWarning = "#b45309"; // Warning variant text color
export const ColorTagTextError = "#b91c1c"; // Error variant text color
export const ColorTagTextInfo = "#1d4ed8"; // Info variant text color
export const ColorTagBorderDefault = "#e2e8f0"; // Default tag border
export const ColorTagBorderSuccess = "#10b981"; // Success variant border
export const ColorTagBorderWarning = "#f59e0b"; // Warning variant border
export const ColorTagBorderError = "#ef4444"; // Error variant border
export const ColorTagBorderInfo = "#3b82f6"; // Info variant border
export const ColorTagBorderFocus = "#0ea5e9"; // Focus ring color
export const ColorTextareaCounterText = "#475569"; // Character counter default
export const ColorTextareaCounterTextOver = "#b91c1c"; // Counter when over limit
export const ColorToastBg = "#ffffff"; // White toast background
export const ColorToastBorder = "#e2e8f0"; // Subtle outer border
export const ColorToastTitle = "#0f172a"; // Toast title text
export const ColorToastDescription = "#475569"; // Toast description text
export const ColorToastCloseHoverBg = "#f1f5f9"; // Close button hover bg
export const ColorToastSuccessBorder = "#10b981"; // Green left accent border
export const ColorToastSuccessIcon = "#047857"; // Green icon color
export const ColorToastErrorBorder = "#ef4444"; // Red left accent border
export const ColorToastErrorIcon = "#b91c1c"; // Red icon color
export const ColorToastWarningBorder = "#f59e0b"; // Amber left accent border
export const ColorToastWarningIcon = "#b45309"; // Amber icon color
export const ColorToastInfoBorder = "#3b82f6"; // Sky blue left accent border
export const ColorToastInfoIcon = "#1d4ed8"; // Sky blue icon color
export const ColorToggleBg = "#f1f5f9"; // Toggle button default background
export const ColorToggleBorder = "#cbd5e1"; // Toggle button border
export const ColorToggleText = "#0f172a"; // Toggle button text
export const ColorToggleHoverBg = "#e2e8f0"; // Toggle button hover background
export const ColorToggleActiveBg = "#0ea5e9"; // Active toggle background
export const ColorToggleActiveText = "#f8fafc"; // Active toggle text
export const ColorToggleActiveBorder = "#0ea5e9"; // Active toggle border
export const ColorToolbarBg = "#ffffff"; // Toolbar background
export const ColorToolbarBorder = "#e2e8f0"; // Toolbar border
export const ColorToolbarBtnText = "#0f172a"; // Button text
export const ColorToolbarBtnHoverBg = "#f1f5f9"; // Button hover background
export const ColorToolbarBtnActiveBg = "#cbd5e1"; // Button active/pressed
export const ColorToolbarLinkText = "#0284c7"; // Link text
export const ColorToolbarLinkHoverText = "#0284c7"; // Link hover text
export const ColorToolbarToggleOnBg = "#f0f9ff"; // Toggle pressed background
export const ColorToolbarToggleOnText = "#0284c7"; // Toggle pressed text
export const ColorToolbarSeparator = "#e2e8f0"; // Separator color
export const ColorTooltipBg = "#0f172a"; // Dark tooltip background
export const ColorTooltipText = "#f8fafc"; // Light text on dark bg
export const ColorTooltipArrow = "#0f172a"; // Arrow matches bg
export const RadiusBaseNone = "0px";
export const RadiusBaseSm = "0.125rem";
export const RadiusBaseBase = "0.25rem";
export const RadiusBaseMd = "0.375rem";
export const RadiusBaseLg = "0.5rem";
export const RadiusBaseXl = "0.75rem";
export const RadiusBase2xl = "1rem";
export const RadiusBase3xl = "1.5rem";
export const RadiusBaseFull = "9999px";
export const RadiusNone = "0px";
export const RadiusSm = "0.125rem";
export const RadiusDefault = "0.25rem";
export const RadiusMd = "0.375rem";
export const RadiusLg = "0.5rem";
export const RadiusXl = "0.75rem";
export const Radius2xl = "1rem";
export const Radius3xl = "1.5rem";
export const RadiusFull = "9999px";
export const RadiusComponentSm = "0.125rem";
export const RadiusComponentMd = "0.375rem";
export const RadiusComponentLg = "0.5rem";
export const RadiusComponentFull = "9999px";
export const RadiusAccordion = "0.5rem"; // 8px item radius
export const RadiusAlert = "0.375rem"; // 6px rounded corners
export const RadiusAlertdlg = "0.5rem"; // AlertDialog border radius
export const RadiusAvatar = "9999px"; // Avatar border radius (circle)
export const RadiusBadge = "9999px";
export const RadiusBannerDismiss = "0.125rem"; // Dismiss button border radius (rounded-sm)
export const RadiusBq = "0.125rem"; // Corner radius
export const RadiusCard = "0.5rem";
export const RadiusChartTooltip = "0.375rem"; // Chart tooltip border radius
export const RadiusCheckbox = "0.125rem"; // 2px subtle rounding
export const RadiusCode = "0.125rem"; // Inline code border radius
export const RadiusCodeBlock = "0.5rem"; // Code block border radius
export const RadiusCmbTrigger = "0.375rem"; // Trigger border radius
export const RadiusCmbContent = "0.5rem"; // Dropdown border radius
export const RadiusCommand = "0.5rem"; // Command palette border radius
export const RadiusCpybtn = "0.375rem"; // Button radius
export const RadiusDatepickerPopover = "0.5rem"; // 8px popover radius
export const RadiusDatepickerDay = "0.375rem"; // 6px day cell radius
export const RadiusDialog = "0.5rem"; // Dialog border radius
export const RadiusDrawer = "0.5rem"; // Drawer top corner radius
export const RadiusDropdownMenu = "0.5rem"; // 8px menu radius
export const RadiusDropdownItem = "0.375rem"; // 6px item radius
export const RadiusFileuploadZone = "0.5rem"; // 8px zone radius
export const RadiusFileuploadItem = "0.375rem"; // 6px file item radius
export const RadiusFileuploadProgress = "9999px"; // Pill progress bar
export const RadiusHl = "0.125rem"; // Highlight border radius
export const RadiusHovercard = "0.5rem"; // HoverCard border radius
export const RadiusImgNone = "0px"; // No radius
export const RadiusImgSm = "0.125rem"; // Small radius
export const RadiusImgMd = "0.375rem"; // Medium radius
export const RadiusImgLg = "0.5rem"; // Large radius
export const RadiusImgFull = "9999px"; // Circle radius
export const RadiusInputotp = "0.375rem"; // Slot border radius
export const RadiusKbd = "0.125rem"; // Key border radius
export const RadiusLdovl = "0.375rem"; // Corner radius (matching container)
export const RadiusMenubarBar = "0.375rem"; // Menubar container radius
export const RadiusMenubarItem = "0.125rem"; // Trigger item radius
export const RadiusModal = "0.5rem"; // 8px rounded corners
export const RadiusNav = "0.375rem"; // Navigation item radius
export const RadiusNavDropdown = "0.5rem"; // Dropdown panel radius
export const RadiusNumberinput = "0.375rem"; // NumberInput border radius
export const RadiusPaginationItem = "0.375rem"; // 6px rounded corners
export const RadiusPopover = "0.5rem"; // 8px rounded corners
export const RadiusProgress = "9999px";
export const RadiusRadioItem = "0.375rem"; // 6px item row rounding
export const RadiusRszHandle = "0.125rem"; // Handle grip radius
export const RadiusScrollareaThumb = "9999px"; // Scrollbar thumb radius
export const RadiusSelectPopover = "0.5rem"; // 8px dropdown radius
export const RadiusSelectItem = "0.375rem"; // 6px item radius
export const RadiusSessionCard = "0.5rem"; // Card border radius
export const RadiusSkeleton = "0.375rem";
export const RadiusSkeletonCircle = "9999px";
export const RadiusSliderTrack = "9999px"; // Slider track radius
export const RadiusSliderThumb = "9999px"; // Slider thumb radius
export const RadiusStatCard = "0.5rem"; // Card border radius
export const RadiusTabsList = "0.5rem"; // 8px pills list radius
export const RadiusTabsTrigger = "0.375rem"; // 6px pills trigger radius
export const RadiusTag = "0.375rem"; // Tag border radius
export const RadiusToast = "0.5rem"; // 8px rounded corners
export const RadiusToggle = "0.375rem"; // Toggle button border radius
export const RadiusToolbarBar = "0.375rem"; // Toolbar container radius
export const RadiusToolbarItem = "0.125rem"; // Button/toggle item radius
export const RadiusTooltip = "0.375rem"; // 6px rounded corners
export const ShadowBaseXs = "0 1px 2px rgba(0, 0, 0, 0.05)";
export const ShadowBaseSm =
  "0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)";
export const ShadowBaseMd =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)";
export const ShadowBaseLg =
  "0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05)";
export const ShadowBaseXl =
  "0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)";
export const ShadowBase2xl = "0 25px 50px rgba(0, 0, 0, 0.25)";
export const ShadowXs = "0 1px 2px rgba(0, 0, 0, 0.05)";
export const ShadowSm =
  "0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)";
export const ShadowMd =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)";
export const ShadowLg =
  "0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05)";
export const ShadowXl =
  "0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)";
export const Shadow2xl = "0 25px 50px rgba(0, 0, 0, 0.25)";
export const ShadowElevationLow =
  "0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)";
export const ShadowElevationMedium =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)";
export const ShadowElevationHigh =
  "0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05)";
export const ShadowElevationOverlay =
  "0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)"; // Modal/dialog content shadow
export const ShadowElevationKey = "0 1px 2px rgba(0, 0, 0, 0.05)"; // Subtle key/pressed element shadow (Kbd)
export const ShadowAlertdlg =
  "0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)"; // AlertDialog panel shadow
export const ShadowCardRaised =
  "0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)";
export const ShadowCardElevated =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)";
export const ShadowCardHover =
  "0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05)";
export const ShadowChartTooltip =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)"; // Chart tooltip shadow
export const ShadowCommand =
  "0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)"; // Command palette shadow
export const ShadowDatepickerPopover =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)"; // Popover elevation
export const ShadowDialog =
  "0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)"; // Dialog panel shadow
export const ShadowDrawer =
  "0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)"; // Drawer elevation shadow
export const ShadowDropdownMenu =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)"; // Menu elevation
export const ShadowHovercard =
  "0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05)"; // HoverCard shadow
export const ShadowKbd = "0 1px 2px rgba(0, 0, 0, 0.05)"; // Key pressed effect shadow
export const ShadowModalContent =
  "0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)"; // Prominent modal shadow
export const ShadowNavDropdown =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)"; // Dropdown panel shadow
export const ShadowPopover =
  "0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05)"; // Elevated popover shadow
export const ShadowSelectPopover =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)"; // Dropdown elevation
export const ShadowSheet =
  "0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)"; // Sheet panel shadow
export const ShadowSwitchThumb =
  "0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)"; // Thumb shadow
export const ShadowTabsTriggerActive =
  "0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)"; // Pills active tab shadow
export const ShadowToast =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)"; // Medium elevation shadow
export const ShadowTooltip =
  "0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.06)"; // Tooltip elevation
export const SpacingBase0 = "0px";
export const SpacingBase1 = "4px";
export const SpacingBase2 = "8px";
export const SpacingBase3 = "12px";
export const SpacingBase4 = "16px";
export const SpacingBase5 = "20px";
export const SpacingBase6 = "24px";
export const SpacingBase7 = "28px";
export const SpacingBase8 = "32px";
export const SpacingBase9 = "36px";
export const SpacingBase10 = "40px";
export const SpacingBase11 = "44px";
export const SpacingBase12 = "48px";
export const SpacingBase14 = "56px";
export const SpacingBase16 = "64px";
export const SpacingBase20 = "80px";
export const SpacingBase24 = "96px";
export const SpacingBase28 = "112px";
export const SpacingBase32 = "128px";
export const SpacingBasePx = "1px";
export const SpacingBase05 = "2px";
export const SpacingBase15 = "6px";
export const SpacingBase25 = "10px";
export const SpacingBase35 = "14px";
export const Spacing3xs = "2px"; // 2px
export const Spacing2xs = "4px";
export const SpacingXs = "8px";
export const SpacingSm = "12px";
export const SpacingMd = "16px";
export const SpacingMdLg = "20px"; // 20px — control element size (checkbox, switch thumb, slider thumb)
export const SpacingLg = "24px";
export const SpacingXl = "32px";
export const Spacing2xl = "48px";
export const Spacing3xl = "64px";
export const SpacingComponentPaddingXs = "8px";
export const SpacingComponentPaddingSm = "12px";
export const SpacingComponentPaddingMd = "16px";
export const SpacingComponentPaddingLg = "24px";
export const SpacingComponentPaddingXl = "32px";
export const SpacingComponentGap2xs = "2px";
export const SpacingComponentGapXs = "4px";
export const SpacingComponentGapSm = "8px";
export const SpacingComponentGapMd = "12px";
export const SpacingComponentGapLg = "16px";
export const SpacingLayoutGutter = "24px";
export const SpacingLayoutSection = "48px";
export const SpacingAccordionTriggerPaddingX = "16px"; // 16px trigger horizontal padding
export const SpacingAccordionTriggerPaddingY = "12px"; // 12px trigger vertical padding
export const SpacingAccordionContentPaddingX = "16px"; // 16px content horizontal padding
export const SpacingAccordionContentPaddingY = "12px"; // 12px content vertical padding
export const SpacingAlertPadding = "16px"; // Alert padding all sides (16px)
export const SpacingAlertGap = "12px"; // Gap between icon and content (12px)
export const SpacingAlertContentGap = "4px"; // Gap between title and description (4px)
export const SpacingAlertdlgPadding = "24px"; // AlertDialog content padding
export const SpacingAlertdlgGap = "12px"; // AlertDialog content gap
export const SpacingBannerPaddingX = "24px"; // Horizontal padding
export const SpacingBannerPaddingY = "16px"; // Vertical padding
export const SpacingBannerGap = "12px"; // Gap between elements
export const SpacingBqPadding = "24px"; // Internal padding
export const SpacingBqBorderWidth = "8px"; // Left border width (4px)
export const SpacingBqCiteGap = "12px"; // Gap before citation
export const SpacingBtnPaddingX = "16px";
export const SpacingBtnPaddingY = "12px";
export const SpacingBtnGap = "8px";
export const SpacingCardPaddingCompact = "12px";
export const SpacingCardPaddingNormal = "16px";
export const SpacingCardPaddingSpacious = "24px";
export const SpacingCardGap = "12px";
export const SpacingCheckboxFieldGap = "8px"; // 8px — Gap between checkbox and content
export const SpacingCheckboxContentGap = "2px"; // 2px — Gap between label and description
export const SpacingCmbContentPadding = "8px"; // Dropdown inner padding
export const SpacingCmbItemPaddingX = "16px"; // Item horizontal padding
export const SpacingCmbItemPaddingY = "12px"; // Item vertical padding
export const SpacingCommandPadding = "12px"; // Command item padding
export const SpacingDatatableToolbarPadding = "16px"; // Toolbar padding
export const SpacingDatatableToolbarGap = "12px"; // Toolbar item gap
export const SpacingDatepickerPopoverPadding = "16px"; // 16px popover inner padding
export const SpacingDatepickerGridGap = "8px"; // 2px gap between day cells
export const SpacingDialogPadding = "24px"; // Dialog content padding
export const SpacingDialogGap = "12px"; // Dialog content gap
export const SpacingDrawerPadding = "24px"; // Drawer content padding
export const SpacingDrawerGap = "12px"; // Drawer section gap
export const SpacingDropdownPadding = "8px"; // 4px inner padding
export const SpacingDropdownItemPaddingX = "12px"; // 12px item horizontal padding
export const SpacingDropdownItemPaddingY = "8px"; // 8px item vertical padding
export const SpacingDropdownItemGap = "8px"; // 8px gap between icon and text
export const SpacingFileuploadZonePadding = "24px"; // 32px zone inner padding
export const SpacingFileuploadFileGap = "8px"; // Gap between file items
export const SpacingHovercardPadding = "16px"; // HoverCard content padding
export const SpacingInputPaddingX = "16px"; // 16px
export const SpacingInputPaddingY = "12px"; // 12px
export const SpacingInputIconInset = "40px"; // 40px – right padding when icon present
export const SpacingInputIconPadding = "12px"; // 12px – icon button internal padding
export const SpacingInputFieldGap = "6px"; // 6px — Gap between Label, Input/Select/Textarea, and Hint in Field wrappers
export const SpacingInputotpGap = "8px"; // Gap between slots
export const SpacingInputotpGroupGap = "12px"; // Gap between groups
export const SpacingLabelIndicatorGap = "2px"; // 2px — Gap between label text and required indicator (*)
export const SpacingLdovlGap = "12px"; // Gap between spinner and text
export const SpacingMenubarPadding = "8px"; // Menubar inner padding
export const SpacingMenubarTriggerPaddingX = "16px"; // Trigger horizontal padding
export const SpacingMenubarTriggerPaddingY = "8px"; // Trigger vertical padding
export const SpacingModalPaddingX = "24px"; // 24px horizontal padding
export const SpacingModalPaddingY = "16px"; // 16px vertical padding
export const SpacingModalGap = "12px"; // 8px footer button gap
export const SpacingPopoverPadding = "16px"; // 16px internal padding
export const SpacingProgressLabelGap = "16px";
export const SpacingRtgGap = "8px"; // Gap between stars
export const SpacingRszHandleSize = "8px"; // Handle hit-area width/height
export const SpacingSinputIconGap = "8px"; // Gap between icon and text
export const SpacingSelectPopoverPadding = "8px"; // 4px inner padding for item list
export const SpacingSelectItemPaddingX = "12px"; // 12px item horizontal padding
export const SpacingSelectItemPaddingY = "8px"; // 8px item vertical padding
export const SpacingSelectItemGap = "8px"; // Gap between icon and text in item
export const SpacingSheetPadding = "24px"; // Sheet content padding
export const SpacingTableCellXCompact = "16px"; // 16px – airy even at compact
export const SpacingTableCellYCompact = "12px"; // 12px – body vertical compact
export const SpacingTableCellXNormal = "24px"; // 24px – generous horizontal
export const SpacingTableCellYNormal = "16px"; // 16px – body vertical normal
export const SpacingTableCellXSpacious = "32px"; // 32px – luxurious horizontal
export const SpacingTableCellYSpacious = "24px"; // 24px – body vertical spacious
export const SpacingTableHeadYCompact = "8px"; // 8px – compact flat header
export const SpacingTableHeadYNormal = "8px"; // 8px – slim elegant header
export const SpacingTableHeadYSpacious = "12px"; // 12px – still compact vs 24px body
export const SpacingTabsListPadding = "8px"; // 4px pills list inner padding
export const SpacingTabsTriggerPaddingX = "16px"; // 16px tab horizontal padding
export const SpacingTabsTriggerPaddingY = "12px"; // 12px tab vertical padding
export const SpacingTabsContentPadding = "16px"; // 16px content padding-top
export const SpacingTabsListGap = "8px"; // 4px gap between pills
export const SpacingTextareaPaddingYSm = "8px"; // 8px – sm size vertical padding
export const SpacingTextareaPaddingYMd = "10px"; // 10px – md size vertical padding
export const SpacingTextareaPaddingYLg = "12px"; // 12px – lg size vertical padding
export const SpacingToastPadding = "16px"; // 16px internal padding
export const SpacingToastGap = "12px"; // 8px gap between icon/content/close
export const SpacingToastViewportPadding = "16px"; // 16px distance from screen edges
export const SpacingToolbarPadding = "8px"; // Toolbar inner padding
export const SpacingToolbarGap = "8px"; // Gap between items
export const SpacingToolbarBtnPaddingX = "16px"; // Button horizontal padding
export const SpacingToolbarBtnPaddingY = "8px"; // Button vertical padding
export const SpacingTooltipPaddingX = "12px"; // 12px horizontal padding
export const SpacingTooltipPaddingY = "8px"; // 8px vertical padding
export const FontBaseFamilySans =
  "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";
export const FontBaseFamilySerif = "'Merriweather', Georgia, serif";
export const FontBaseFamilyMono = "'JetBrains Mono', 'Fira Code', monospace";
export const FontBaseSizeXs = "0.75rem";
export const FontBaseSizeSm = "0.875rem";
export const FontBaseSizeBase = "1rem";
export const FontBaseSizeLg = "1.125rem";
export const FontBaseSizeXl = "1.25rem";
export const FontBaseSize2xl = "1.5rem";
export const FontBaseSize3xl = "1.875rem";
export const FontBaseSize4xl = "2.25rem";
export const FontBaseSize5xl = "3rem";
export const FontBaseWeightLight = 300;
export const FontBaseWeightNormal = 400;
export const FontBaseWeightMedium = 500;
export const FontBaseWeightSemibold = 600;
export const FontBaseWeightBold = 700;
export const FontBaseLineHeightXs = "18px";
export const FontBaseLineHeightSm = "21px";
export const FontBaseLineHeightBase = "24px";
export const FontBaseLineHeightLg = "27px";
export const FontBaseLineHeightXl = "30px";
export const FontBaseLineHeight2xl = "36px";
export const FontBaseLineHeight3xl = "45px";
export const FontBaseLineHeight4xl = "54px";
export const FontBaseLineHeight5xl = "72px";
export const FontBaseLetterSpacingTight = "-0.025em";
export const FontBaseLetterSpacingNormal = "0em";
export const FontBaseLetterSpacingWide = "0.025em";
export const FontSizeXs = "0.75rem";
export const FontSizeSm = "0.875rem";
export const FontSizeBase = "1rem";
export const FontSizeLg = "1.125rem";
export const FontSizeXl = "1.25rem";
export const FontSize2xl = "1.5rem";
export const FontSize3xl = "1.875rem";
export const FontSize4xl = "2.25rem";
export const FontSize5xl = "3rem";
export const FontWeightLight = 300;
export const FontWeightNormal = 400;
export const FontWeightMedium = 500;
export const FontWeightSemibold = 600;
export const FontWeightBold = 700;
export const FontFamilySans =
  "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";
export const FontFamilySerif = "'Merriweather', Georgia, serif";
export const FontFamilyMono = "'JetBrains Mono', 'Fira Code', monospace";
export const FontLineHeightXs = "18px";
export const FontLineHeightSm = "21px";
export const FontLineHeightBase = "24px";
export const FontLineHeightLg = "27px";
export const FontLineHeightXl = "30px";
export const FontLineHeight2xl = "36px";
export const FontLineHeight3xl = "45px";
export const FontLineHeight4xl = "54px";
export const FontLineHeight5xl = "72px";
export const FontLetterSpacingTight = "-0.025em";
export const FontLetterSpacingNormal = "0em";
export const FontLetterSpacingWide = "0.025em";
export const FontComponentSizeXs = "0.75rem";
export const FontComponentSizeSm = "0.875rem";
export const FontComponentSizeMd = "1rem";
export const FontComponentSizeLg = "1.125rem";
export const FontComponentWeightNormal = 400;
export const FontComponentWeightMedium = 500;
export const FontComponentWeightSemibold = 600;
export const FontComponentWeightBold = 700;
export const FontComponentLineHeightXs = "18px";
export const FontComponentLineHeightSm = "21px";
export const FontComponentLineHeightMd = "24px";
export const FontComponentLineHeightLg = "27px";
export const FontHeadingSizeXs = "1rem";
export const FontHeadingSizeSm = "1.125rem";
export const FontHeadingSizeMd = "1.25rem";
export const FontHeadingSizeLg = "1.5rem";
export const FontHeadingSizeXl = "1.875rem";
export const FontHeadingSize2xl = "2.25rem";
export const FontHeadingH1Size = "2.25rem"; // h1 font size (2.25rem / text-4xl)
export const FontHeadingH1Weight = 700; // h1 font weight (700)
export const FontHeadingH2Size = "1.875rem"; // h2 font size (1.875rem / text-3xl)
export const FontHeadingH2Weight = 700; // h2 font weight (700)
export const FontHeadingH3Size = "1.5rem"; // h3 font size (1.5rem / text-2xl)
export const FontHeadingH3Weight = 600; // h3 font weight (600)
export const FontHeadingH4Size = "1.25rem"; // h4 font size (1.25rem / text-xl)
export const FontHeadingH4Weight = 600; // h4 font weight (600)
export const FontHeadingH5Size = "1.125rem"; // h5 font size (1.125rem / text-lg)
export const FontHeadingH5Weight = 500; // h5 font weight (500)
export const FontHeadingH6Size = "1rem"; // h6 font size (1rem / text-base)
export const FontHeadingH6Weight = 500; // h6 font weight (500)
export const FontBodySize = "1rem";
export const FontCaptionSize = "0.75rem";
export const FontAvatarFallbackWeight = 500; // Fallback initials font weight (500)
export const FontAvatarSmSize = "0.75rem"; // Fallback text size sm (text-xs)
export const FontAvatarMdSize = "0.875rem"; // Fallback text size md (text-sm)
export const FontAvatarLgSize = "1rem"; // Fallback text size lg (text-base)
export const FontAvatarXlSize = "1.125rem"; // Fallback text size xl (text-lg)
export const FontBadgeWeight = 500; // Font weight 500 (medium)
export const FontBannerSize = "0.875rem"; // Banner content font size (text-sm)
export const FontBqCiteSize = "0.875rem"; // Citation font size (14px)
export const FontBqCiteWeight = 500; // Citation author font weight (500)
export const FontBtnWeight = 500; // Button font weight (500)
export const FontCheckboxLabelSize = "0.875rem"; // Label font size 14px (text-sm)
export const FontCheckboxLabelWeight = 500; // Label font weight 500 (font-medium)
export const FontCheckboxDescSize = "0.75rem"; // Description font size 12px (text-xs)
export const FontCheckboxDescWeight = 400; // Description font weight 400
export const FontCheckboxLabelLineHeight = "21px"; // 20px
export const FontCheckboxDescLineHeight = "18px"; // 18px
export const FontCodeSize = "0.875rem"; // Code font size (14px)
export const FontInputWeight = 400; // Font weight 400 (normal)
export const FontInputotpSize = "0.875rem"; // OTP digit font size (text-sm)
export const FontInputotpWeight = 500; // OTP digit font weight (500)
export const FontKbdSmSize = "11px"; // Kbd sm font size (11px, no L3 equivalent)
export const FontKbdMdSize = "0.75rem"; // Kbd md font size (12px)
export const FontKbdLgSize = "0.875rem"; // Kbd lg font size (14px)
export const FontLabelSize = "0.875rem"; // Label font size (14px)
export const FontLabelWeight = 500; // Label font weight (500)
export const FontNumberinputWeight = 500; // Input value font weight (500)
export const FontProgressLabelSize = "0.875rem"; // ProgressField label font size (text-sm)
export const FontProgressLabelWeight = 500; // ProgressField label font weight (500)
export const FontProgressValueSize = "0.875rem"; // ProgressField value font size (text-sm)
export const FontSliderValueSize = "0.875rem"; // Slider value display font size (text-sm)
export const FontSliderValueWeight = 500; // Slider value display font weight (500)
export const FontSpinnerLabelSize = "0.875rem"; // Spinner label font size (text-sm)
export const FontSwitchLabelSize = "0.875rem"; // SwitchField label font size (text-sm)
export const FontSwitchLabelWeight = 500; // SwitchField label font weight (500)
export const FontSwitchDescSize = "0.75rem"; // SwitchField description font size (text-xs)
export const FontTagWeight = 500; // Tag font weight (500)
export const FontTagSmSize = "0.75rem"; // Tag sm font size (12px)
export const FontTagMdSize = "0.875rem"; // Tag md font size (14px)
export const FontTextBodySize = "1rem"; // Body variant font size (text-base)
export const FontTextCaptionSize = "0.875rem"; // Caption variant font size (text-sm)
export const FontTextSmallSize = "0.75rem"; // Small variant font size (text-xs)
export const FontTextMutedSize = "0.875rem"; // Muted variant font size (text-sm)
export const FontToggleWeight = 500; // Toggle/ToggleGroup font weight (500)
export const SizingHeightSm = "36px";
export const SizingHeightMd = "40px";
export const SizingHeightLg = "44px";
export const SizingPaddingXSm = "12px";
export const SizingPaddingXMd = "16px";
export const SizingPaddingXLg = "32px";
export const SizingPaddingYSm = "6px";
export const SizingPaddingYMd = "8px";
export const SizingPaddingYLg = "10px";
export const SizingPaddingYXl = "12px";
export const SizingGapSm = "6px";
export const SizingGapMd = "8px";
export const SizingGapLg = "10px";
export const SizingBorderWidthDefault = "1px";
export const SizingBorderWidthThick = "2px";
export const SizingComponentHeightSm = "36px";
export const SizingComponentHeightMd = "40px";
export const SizingComponentHeightLg = "44px";
export const SizingComponentPaddingXSm = "12px";
export const SizingComponentPaddingXMd = "16px";
export const SizingComponentPaddingXLg = "32px";
export const SizingComponentPaddingYSm = "6px";
export const SizingComponentPaddingYMd = "8px";
export const SizingComponentPaddingYLg = "10px";
export const SizingComponentPaddingYXl = "12px";
export const SizingComponentGapSm = "6px";
export const SizingComponentGapMd = "8px";
export const SizingComponentGapLg = "10px";
export const SizingComponentIconSm = "16px";
export const SizingComponentIconControl = "20px"; // 20px — checkbox, switch thumb, slider thumb
export const SizingComponentIconMd = "24px";
export const SizingComponentIconLg = "32px";
export const SizingComponentIconXl = "48px";
export const SizingComponentTrackSm = "4px";
export const SizingComponentTrackMd = "8px";
export const SizingComponentTrackLg = "12px";
export const SizingComponentBorderWidthDefault = "1px";
export const SizingComponentBorderWidthThick = "2px";
export const SizingAlertBorderWidth = "4px"; // Left accent border width (4px)
export const SizingAlertFontSize = "0.875rem"; // Text font size (14px)
export const SizingAlertLineHeight = "21px"; // Text line height (21px)
export const SizingAlertTitleWeight = 600; // Title font weight (600)
export const SizingAlertDescWeight = 400; // Description font weight (400)
export const SizingAvatarSm = "36px"; // Avatar size sm (h-9 = 36px)
export const SizingAvatarMd = "40px"; // Avatar size md (h-10 = 40px)
export const SizingAvatarLg = "44px"; // Avatar size lg (h-11 = 44px)
export const SizingAvatarXl = "48px"; // Avatar size xl (48px) — TODO: Add sizing.component.height.xl to L3 for 64px (h-16)
export const SizingAvatarBorderWidth = "1px"; // Avatar border width (1px)
export const SizingBadgeBorderWidth = "1px"; // Badge border width (1px)
export const SizingBadgeSmPaddingX = "12px";
export const SizingBadgeSmPaddingY = "6px";
export const SizingBadgeSmFontSize = "0.875rem";
export const SizingBadgeSmLineHeight = "21px"; // 21px
export const SizingBadgeMdPaddingX = "16px";
export const SizingBadgeMdPaddingY = "6px";
export const SizingBadgeMdFontSize = "0.875rem";
export const SizingBadgeMdLineHeight = "21px"; // 21px
export const SizingBadgeLgPaddingX = "16px";
export const SizingBadgeLgPaddingY = "8px";
export const SizingBadgeLgFontSize = "1rem";
export const SizingBadgeLgLineHeight = "24px"; // 24px
export const SizingBtnSmHeight = "36px";
export const SizingBtnSmPaddingX = "12px";
export const SizingBtnSmPaddingY = "6px";
export const SizingBtnSmGap = "6px";
export const SizingBtnSmFontSize = "0.875rem";
export const SizingBtnSmLineHeight = "21px";
export const SizingBtnSmRadius = "0.375rem";
export const SizingBtnMdHeight = "40px";
export const SizingBtnMdPaddingX = "16px";
export const SizingBtnMdPaddingY = "8px";
export const SizingBtnMdGap = "8px";
export const SizingBtnMdFontSize = "1rem";
export const SizingBtnMdLineHeight = "24px";
export const SizingBtnMdRadius = "0.375rem";
export const SizingBtnLgHeight = "44px";
export const SizingBtnLgPaddingX = "32px";
export const SizingBtnLgPaddingY = "10px";
export const SizingBtnLgGap = "10px";
export const SizingBtnLgFontSize = "1.125rem";
export const SizingBtnLgLineHeight = "27px";
export const SizingBtnLgRadius = "0.375rem";
export const SizingBtnBorderWidth = "1px";
export const SizingCheckboxBoxSize = "20px"; // Checkbox box size (20px)
export const SizingCheckboxIconSize = "16px"; // Check icon size inside checkbox (16px)
export const SizingCheckboxBorderWidth = "2px"; // 2px
export const SizingCpybtnSm = "28px"; // CopyButton size sm (compact icon-only)
export const SizingCpybtnMd = "32px"; // CopyButton size md
export const SizingCpybtnLg = "36px"; // CopyButton size lg
export const SizingDatepickerDaySize = "36px"; // Day cell width/height
export const SizingIconSm = "16px"; // Small icon (16x16)
export const SizingIconMd = "20px"; // Medium icon (20x20) — default
export const SizingIconLg = "24px"; // Large icon (24x24)
export const SizingIconXl = "32px"; // Extra large icon (32x32)
export const SizingInputBorderWidth = "1px"; // 1px
export const SizingInputSmHeight = "36px"; // 36px – matches Button sm
export const SizingInputSmFontSize = "0.875rem"; // 0.875rem
export const SizingInputSmLineHeight = "21px"; // 21px
export const SizingInputSmRadius = "0.375rem"; // 6px
export const SizingInputMdHeight = "40px"; // 40px – matches Button md
export const SizingInputMdFontSize = "1rem"; // 1rem
export const SizingInputMdLineHeight = "24px"; // 24px
export const SizingInputMdRadius = "0.375rem"; // 6px
export const SizingInputLgHeight = "44px"; // 44px – matches Button lg
export const SizingInputLgFontSize = "1.125rem"; // 1.125rem
export const SizingInputLgLineHeight = "27px"; // 27px
export const SizingInputLgRadius = "0.375rem"; // 6px
export const SizingInputotpSlotSize = "40px"; // Slot width and height (40px)
export const SizingInputotpBorderWidth = "1px"; // Slot border width (1px)
export const SizingKbdBorderWidth = "1px"; // Key border width (1px)
export const SizingNumberinputBorderWidth = "1px"; // NumberInput border width (1px)
export const SizingPaginationItemSize = "36px"; // Page button width & height (36px square)
export const SizingPaginationFontSize = "0.875rem"; // Page button font size
export const SizingProgressSmHeight = "4px";
export const SizingProgressMdHeight = "8px";
export const SizingProgressLgHeight = "12px";
export const SizingRadioButtonSize = "16px"; // Radio button outer size (16px via L3) — TODO: Need L3 token for 20px (h-5 w-5). Currently using icon.sm=16px as closest available
export const SizingRadioDotSize = "12px"; // Radio inner dot size (12px)
export const SizingRtgSm = "16px"; // Star size sm
export const SizingRtgMd = "24px"; // Star size md
export const SizingRtgLg = "32px"; // Star size lg
export const SizingSkeletonCircleSm = "36px"; // Skeleton circle sm (36px)
export const SizingSkeletonCircleMd = "40px"; // Skeleton circle md (40px)
export const SizingSkeletonCircleLg = "44px"; // Skeleton circle lg (44px)
export const SizingSliderTrackHeight = "8px"; // Slider track height (8px)
export const SizingSliderThumbSize = "20px"; // Slider thumb size (20px)
export const SizingSliderThumbBorderWidth = "2px"; // Slider thumb border width (2px)
export const SizingSpinnerSm = "16px";
export const SizingSpinnerMd = "24px";
export const SizingSpinnerLg = "32px";
export const SizingSpinnerXl = "48px";
export const SizingSwitchTrackHeight = "24px"; // Switch track height (24px = h-6)
export const SizingSwitchTrackWidth = "44px"; // Switch track width (44px = w-11)
export const SizingSwitchThumbSize = "20px"; // Switch thumb size (20px)
export const SizingTagBorderWidth = "1px"; // Tag border width (1px)
export const SizingTextareaMinHeight = "100px"; // Default minimum height
export const SizingTextareaMaxHeight = "400px"; // Auto-resize maximum
export const SizingToggleSmHeight = "36px"; // Toggle item height sm
export const SizingToggleSmPaddingX = "12px"; // Toggle item horizontal padding sm
export const SizingToggleSmFontSize = "0.875rem"; // Toggle item font size sm
export const SizingToggleMdHeight = "40px"; // Toggle item height md
export const SizingToggleMdPaddingX = "16px"; // Toggle item horizontal padding md
export const SizingToggleMdFontSize = "0.875rem"; // Toggle item font size md
export const SizingToggleLgHeight = "44px"; // Toggle item height lg
export const SizingToggleLgPaddingX = "32px"; // Toggle item horizontal padding lg
export const SizingToggleLgFontSize = "1rem"; // Toggle item font size lg
